server:
  port: 9091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: purchase
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jxc?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: admin
info:
  app.name: purchase
  author: yqd
# MyBatis
mybatis:
  type-aliases-package: com.inventory.entity
  mapper-locations: classpath:/mapper/*.xml