server:
  port: 8080
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
info:
  app.name: zuulservice
  author: yqd
zuul:
  ignored-services: "*"
#  prefix: /api
  routes:
    purchase: /purchase/**
    feign: /api/**