server:
  port: 8888
spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka